# Generated by Django 4.2.16 on 2024-09-26 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'managed': False},
        ),
    ]
