# Generated by Django 4.2.16 on 2024-09-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='weekday',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='ongoing', max_length=10),
        ),
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=models.DateField(db_column='Date', null=True),
        ),
        migrations.AlterField(
            model_name='referee',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='referee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='referee',
            name='level',
            field=models.CharField(choices=[('0', 'Trainee'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='referee',
            name='zip_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
