# Generated by Django 4.2.16 on 2024-09-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0002_availability_weekday_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='match_time',
            field=models.TimeField(null=True),
        ),
    ]
