# Generated by Django 4.2.16 on 2024-09-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0003_alter_appointmentmanagementappointment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referee',
            name='level',
        ),
        migrations.AddField(
            model_name='referee',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='referee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='referee',
            name='zip_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
