# Generated by Django 4.2.16 on 2024-10-06 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0003_appointment_appointment_time_match_match_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='availableID',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='availability',
            name='referee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='appointment_management.referee'),
        ),
    ]
