# Generated by Django 4.2.16 on 2024-10-07 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0004_alter_availability_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='availability',
            name='availableType',
            field=models.CharField(choices=[('A', 'Available'), ('U', 'Unavailable')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='duration',
            field=models.IntegerField(db_column='Duration', null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appointment_management.referee'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
