# Generated by Django 4.2.16 on 2024-10-07 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0005_alter_availability_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='referee',
            field=models.ForeignKey(db_column='referee_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='appointment_management.referee'),
        ),
    ]
