# Generated by Django 4.2.16 on 2024-10-07 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0007_alter_availability_referee_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together=set(),
        ),
    ]
